#!/bin/sh

##
## This startup file is automatically generated by tools/scripts/createScript.pl
##

. "$(dirname $0)/../../setEnv.sh"

APPLICATION_DIR=strategyagent

cd ${METC_HOME}/${APPLICATION_DIR}

THE_CLASSPATH=./conf
for file in `ls -1 ./lib/*.jar`
do
    THE_CLASSPATH=${THE_CLASSPATH}:${file}
done

#-Dport=7496\
java -Xms384m -Xmx600m -Dorg.marketcetera.appDir=${METC_HOME}/${APPLICATION_DIR}\
 -Dstrategy.classpath=${METC_HOME}/${APPLICATION_DIR}/src\
 -Dinput.symbols=${METC_HOME}/${APPLICATION_DIR}/src/xlk.us.csv\
 -Dibconf.file=${METC_HOME}/${APPLICATION_DIR}/src/conf-base.properties\
 -DtickFrequency=5\
 -Dfile.encoding=UTF-8\
 -Dport=4001\
 -DclientId=9\
 -cp "${THE_CLASSPATH}"\
 org.marketcetera.strategyagent.StrategyAgent $*
